[licenses]
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "MPL-2.0",        # Mozilla Public License (ucs2 crate)
    "Unicode-3.0",    # Unicode License (unicode-ident crate)
]

[bans]
multiple-versions = "warn"

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-registry = "deny"
unknown-git = "deny"
