name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly, 1.81.0]  # stable, beta, nightly, and MSRV
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: x86_64-unknown-uefi
          components: clippy, rustfmt
        
      - name: cache rust toolchain
        uses: Swatinem/rust-cache@v2

      - name: cargo deny
        uses: EmbarkStudios/cargo-deny-action@v2

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --target x86_64-unknown-uefi --all-targets -- -D warnings

      - name: cargo build
        run: |
          cargo build --target x86_64-unknown-uefi
          cargo build --release --target x86_64-unknown-uefi

      - name: upload artifacts
        if: matrix.rust == 'stable'
        uses: actions/upload-artifact@v4
        with:
          name: uefi-reset
          path: target/x86_64-unknown-uefi/release/*.efi
