name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-uefi
        
      - name: cache rust toolchain
        uses: Swatinem/rust-cache@v2

      - name: cargo build
        run: cargo build --release --target x86_64-unknown-uefi

      - name: create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create --generate-notes ${{ github.ref_name }} target/x86_64-unknown-uefi/release/*.efi
            
